name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: ./gradlew build --no-daemon

      - name: Deploy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          
        run: |
          # Aquí puedes ejecutar comandos de despliegue que utilicen la variable de entorno MONGODB_URI
